@startuml ipc_receive_seq_diagram

title IPC Machine: Receiving new TimeInfo data

hide footbox

autonumber "<font color=red><b>[00]"
autoactivate on

legend top left
    |= Color        |= Description                  |
    |<#LightPink>   | IPC components                |
    |<#LightCoral>  | score::communication          |
    |<#LightSalmon> | Client Application            |
endlegend

box mw::time::svt #e6ffe6
    participant "Business logic" as mw_worker #LightSalmon
    participant "IPCMachine:receiver" as ipc_receiver #LightPink
end box

participant "score::communication" as score_comm #LightCoral

mw_worker -> ipc_receiver: receive()
ipc_receiver -> score_comm: Receive()
score_comm --> ipc_receiver: TimeInfo
ipc_receiver --> mw_worker: TimeInfo

@enduml
