@startuml ipc_publish_seq_diagram

title IPC Machine: Publishing new TimeInfo data

hide footbox

autonumber "<font color=red><b>[00]"
autoactivate on

legend top left
    |= Color     |= Description                  |
    |<#LightCyan>| TimeDaemon members            |
    |<#LightPink>| IPC components                |
    |<#WhiteSmoke>| Shared Memory                |
endlegend

box VehicleTimeDaemon #LightYellow
    participant "MessageBroker" as broker #LightCyan
    participant "IPCMachine:publisher" as ipc_publisher #LightPink
end box

participant "shmem" as shared_memory #WhiteSmoke

broker -> ipc_publisher: newTimeData(TimeInfo)
alt if the data was updated
    ipc_publisher -> ipc_publisher: serialize data
    ipc_publisher -> shared_memory: store(TimeInfo)
    note right
        All data, which is needed by the Apps, like
        1. current Vehicle time
        2. local time
        3. status
        4. sync/fup and pdelay frames content
        5. rate and so on
        shall be stored here
    end note
    shared_memory --> ipc_publisher: success
end
ipc_publisher --> broker

@enduml
