@startuml message_broker_initialization_sequence_diagram

title MessageBroker: Initialization Sequence

hide footbox

autonumber "<font color=red><b>[00]"

legend top left
    |= Color        |= Description                  |
    |<#LightCyan>   | TimeDaemon members            |
    |<#PaleTurquoise> | MessageBroker               |
    |<#Beige>       | Base classes                  |
endlegend

participant "TimeBaseHandler" as tb_handler #LightCyan
participant "MessageBroker" as broker #PaleTurquoise
participant "Producer" as producer #Beige

== MessageBroker Construction ==

tb_handler -> broker ** : create()
activate tb_handler
activate broker
broker --> tb_handler
deactivate broker
deactivate tb_handler

== Setup Subscriptions ==

tb_handler -> broker : AddSubscriber(topic, Consumer*)
activate tb_handler
activate broker
broker -> broker : Store subscription
note right
    Register Consumer to receive
    messages on topic.
    All sw components, who are interested
    in "particular" topic should be
    registered here.
end note
broker --> tb_handler
deactivate broker
deactivate tb_handler

== Setup Producers ==

tb_handler -> broker : AddProducer("topic, Producer*)
activate tb_handler
activate broker
broker -> producer : SetPublishCallback(broker::OnNewData)
activate producer
note right
    Register Producer to callback
    to publish to topic
    All sw components, who are contributing
    in "particular" topic should be
    registered here.
end note
producer --> broker
deactivate producer
broker --> tb_handler
deactivate broker
deactivate tb_handler

@enduml
