@startuml mw_time_svt_class_diagram

title mw::time::svt: Class Diagram

legend top left
    |= Color            |= Description                     |
    | <#LightGreen>     | Middleware components            |
    | <#LightPink>      | IPC components                   |
endlegend


class "TimeInfo" as time_info #Beige {
    +ptp: uint64
    +local_time: uint64
    +status: int
    +sync_fup_data: int
    +pdelay_data: int
}

class "TimeStatus" as time_status #LightGreen {
    +ptp: uint64
    +status: int
}

class "IPCMachine:receiver" as ipc_machine_receiver #LightPink {
    +receive(): TimeInfo
}

class "score::time::svt" as mw_svt #LightGreen {
    +Now(): TimeStatus
}

ipc_machine_receiver --> time_info : processes
mw_svt *-- ipc_machine_receiver : contains
mw_svt --> time_status : provides

@enduml
