@startuml message_broker_workflow_sequence_diagram

title Message Broker: Workflow Diagram

hide footbox

autonumber "<font color=red><b>[00]"

legend top left
    |= Color          |= Description                  |
    |<#PaleTurquoise> | MessageBroker               |
    |<#Beige>         | Base classes                  |
endlegend

box VehicleTimeDaemon #LightYellow
    participant "Producer<T>" as machine_pub #Beige
    participant "MessageBroker" as msg_broker #PaleTurquoise
    participant "Consumer<T>" as machine_sub #Beige
end box


machine_pub -> msg_broker : publish(topic, PTPTimeInfo)
activate msg_broker

msg_broker -> msg_broker: search for subscribers\non provided <topic>

loop for all found subscribers
    msg_broker -> machine_sub: callback(PTPTimeInfo)
    activate machine_sub
    note right machine_sub: Process PTPTimeInfo data
    machine_sub -> msg_broker:
    deactivate machine_sub
end
msg_broker --> machine_pub

deactivate msg_broker

@enduml
