@startuml dd_deployment_diagram

title Deployment view

node "Application Layer" {
    [Business logic] as app_bl
    [mw::time::svt] <<library>> as mw
}
node "PTP Daemon" {
    [ptpd] <<daemon>> as ptpd
}
node "VehicleTimeDaemon" {
    [MessageBroker]  as msg_broker
    [VerificationMachine]  as verification_machine
    [PTP machine] as ptp_machine
    [IPC] as ipc
}

ptpd -[#blue]-> ptp_machine : PTP time updates\n(via shmem and devctl)
ptp_machine -[#green]-> verification_machine: Time information
verification_machine -[#green]-> ipc: Time information
ipc -[#green]-> mw: Time information
mw-[#orange]-> app_bl : Now()

@enduml
