@startuml sad_deployment_diagram

title Deployment view

node "IPN1x" {
    node "Application Layer" {
        [Business logic] as app_bl
        [mw::time::svt] <<library>> as mw
    }
    node "Diagnostic App Layer" {
        [Diag jobs business logic] as diag_bl
        [mw::time::svt::ext] <<library>> as mw_ext
    }
    node "PTP Daemon" {
        [ptpd] <<daemon>> as ptpd
    }
    node "VehicleTimeDaemon" {
        [VerificationMachine]  as verification_machine
        [PTP machine] as ptp_machine
    }
    [EMAC] <<hw clock>> as hw_counter
}
node "Time Grand Master" {
    [PTP Grandmaster Clock] <<device>> as ptp_gm
}
[DLT] <<records>> as dlt_records


ptp_gm -[#purple]-> ptpd : PTP sync messages
ptpd ..> hw_counter : Updates local hw timer
ptpd -[#blue]-> ptp_machine : PTP time updates\n(via shmem and devctl)
ptp_machine -[#green]-> verification_machine: Time information
verification_machine -[#green]-> mw: Time information
verification_machine -[#green]-> mw_ext: Time information
verification_machine -[#green]-> dlt_records: Data for post analysis
mw-[#orange]-> app_bl : Now()
mw_ext-[#orange]-> diag_bl : Now(), Callbacks()

@enduml
