@startuml app_init_seq_diagram

title Application: Initialization Sequence

hide footbox
autoactivate on

autonumber "<font color=red><b>[00]"

legend top left
    |= Color        |= Description           |
    |<#LightCyan>   | TimeDaemon members     |
    |<#LightGreen>  | Middleware components  |
    |<#Beige>       | SW components          |
endlegend

participant "LifecycleManager" as lcm #LightGreen
participant "TimeDaemon" as vtd_app #LightCyan
participant "TimebaseHandler" as tb_handler #LightCyan
participant "Components" as components #Beige

== TimeDaemon Construction ==

lcm -> vtd_app ** : Construct TimeDaemon()
activate vtd_app
vtd_app -> tb_handler ** : create TimebaseHandler()
activate tb_handler

tb_handler -> components ** : create all components
note right of components
    TimebaseHandler creates:
    - MessageBroker
    - PtpMachine
    - VerificationMachine
    - ControlFlowDivider
    - IPCPublisher
end note

tb_handler --> vtd_app : TimebaseHandler instance
deactivate tb_handler
vtd_app --> lcm : TimeDaemon instance
deactivate vtd_app

== Initialization Phase ==

lcm -> vtd_app : Initialize(context)
activate vtd_app

vtd_app -> tb_handler : Initialize()
activate tb_handler

tb_handler -> tb_handler : Setup MessageBroker\nsubscriptions
note right
    Connect components via topics:
    - input_ptp_data
    - raw_ptp_data
    - validated_ptp_data
end note

tb_handler --> vtd_app
deactivate tb_handler

vtd_app --> lcm
deactivate vtd_app

note right of tb_handler
    All components created and connected,
    but not yet started
end note

@enduml
