@startuml dd_data_control_flow_diagram

title VehicleTimeDaemon: Multi-Timebase Data Flow

hide footbox

legend top left
    |= Color        |= Description                  |
    |<#LightBlue>   | PTP Pipeline                  |
    |<#RosyBrown>   | Absolute Time Pipeline        |
    |<#LightGreen>  | Middleware                    |
    |<#LightSalmon> | Application                   |
endlegend

participant "ptpd" as ptpd #PeachPuff
participant "SDat SOMEIP" as sdat_someip #PeachPuff

box TimeDaemon: PTP Pipeline #LightCyan
    participant "PTPMachine" as ptp_machine #LightBlue
    participant "ControlFlow &\nVerification" as ptp_pipeline #LightBlue
    participant "SharedMemory\nPTP" as shmem_ptp #WhiteSmoke
end box

box TimeDaemon: Absolute Time Pipeline #MistyRose
    participant "AbsTimeMachine" as abs_machine #RosyBrown
    participant "ControlFlow &\nVerification" as abs_pipeline #RosyBrown
    participant "SharedMemory\nAbsTime" as shmem_abs #WhiteSmoke
end box

box Application #e6ffe6
    participant "score::time::svt" as mw_svt #LightGreen
    participant "score::time::abs" as mw_abs #LightGreen
    participant "Application" as app #LightSalmon
end box

== PTP Time Flow ==

ptpd -> ptp_machine : PTP data
ptp_machine -> ptp_pipeline : Validate & process
ptp_pipeline -> shmem_ptp : Write PtpTimeInfo

app -> mw_svt : Now()
mw_svt -> shmem_ptp : Read
shmem_ptp --> mw_svt : PtpTimeInfo
mw_svt --> app : Current Vehicle Time

== Absolute Time Flow ==

sdat_someip -> abs_machine : Absolute time data
abs_machine -> abs_pipeline : Validate & process
abs_pipeline -> shmem_abs : Write AbsTimeInfo

app -> mw_abs : Now()
mw_abs -> shmem_abs : Read
shmem_abs --> mw_abs : AbsTimeInfo
mw_abs --> app : Current Absolute Time

@enduml
