@startuml mw_time_receive_seq_diagram

title mw::time::svt: Providing new Vehicle Time to Applications

hide footbox

autonumber "<font color=red><b>[00]"
autoactivate on

legend top left
    |= Color        |= Description                  |
    |<#LightPink>   | IPC components                |
    |<#LightSalmon> | Client Application            |
    |<#LightGreen>  | Middleware components         |
endlegend

box Application #e6ffe6
    participant "Business logic" as app #LightSalmon
    participant "score::time::svt" as mw_svt #LightGreen
    participant "shared_buffer" as mw_buffer #LightGreen
    participant "worker\nthread" as mw_worker #LightGreen
    participant "IPCMachine:receiver" as ipc_receiver #LightPink
end box

loop each 50 msec
    mw_worker -> ipc_receiver: receive()
    ipc_receiver --> mw_worker: TimeInfo
    mw_worker --> mw_buffer: store TimeInfo
end

app -> mw_svt: Now()
mw_svt -> mw_buffer: read()
mw_buffer --> mw_svt: TimeInfo
mw_svt -> mw_svt: handleNewData()
note right
    Adjusts the ptp time with current local time
    and provides the current time to the application.
end note
mw_svt --> app: Current Vehicle Time

@enduml
