@startuml dd_deployment_diagram

title Deployment view

node "Application Layer" {
    [Business logic] as app_bl
    [mw::time::svt] <<library>> as mw
}

node "Application Layer\n(Absolute Time)" {
    [Business logic] as app_abs_bl
    [mw::time::abs] <<library>> as mw_abs
}

node "PTP Daemon" {
    [ptpd] <<daemon>> as ptpd
}

node "SDat SOMEIP" {
    [Time provider] <<service>> as time_provider
}

node "TimeDaemon" {
    [MessageBroker]  as msg_broker

    package "PTP Pipeline" {
        [PTP machine] as ptp_machine
        [ControlFlowDivider PTP] as cf_ptp
        [VerificationMachine PTP]  as verification_machine_ptp
        [IPC_PTP] as ipc_ptp
    }

    package "Absolute Time Pipeline" {
        [AbsoluteTimeMachine]  as abs_time_machine
        [ControlFlowDivider AbsTime] as cf_abs
        [VerificationMachine AbsTime]  as verification_machine_abs
        [IPC_AbsTime] as ipc_abs
    }
}

' PTP Pipeline
ptpd -[#blue]-> ptp_machine : PTP time updates\n(via shmem and devctl)
ptp_machine -[#green]-> cf_ptp : PTP data
cf_ptp -[#green]-> verification_machine_ptp: PTP data
verification_machine_ptp -[#green]-> ipc_ptp: Verified PTP time
ipc_ptp -[#green]-> mw: PTP time information
mw -[#orange]-> app_bl : Now()

' Absolute Time Pipeline
time_provider -[#blue]-> abs_time_machine : Absolute time\n(UTC/TAI/GPS)
abs_time_machine -[#purple]-> cf_abs : Absolute time data
cf_abs -[#purple]-> verification_machine_abs: Absolute time data
verification_machine_abs -[#purple]-> ipc_abs: Verified absolute time
ipc_abs -[#purple]-> mw_abs : Absolute time
mw_abs -[#orange]-> app_abs_bl : Now()

@enduml
