# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: Build / Linux

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  workflow_call:
jobs:
  linux-build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        config: [time-x86_64-linux, time-arm64-linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}-${{ matrix.config }}
          repository-cache: true
          cache-save: ${{ github.event_name == 'push' }}

      - name: Build with Bazel
        run: |
          bazel build --keep_going --verbose_failures --config ${{ matrix.config }} -- //score/... //examples/...
